In [1]:
import pandas as pd
import datetime

In [2]:
ip_file = "prediction_names.csv"
ip_df = pd.read_csv(ip_file, delimiter=";")
obs_file = "observation.csv"
obs_df = pd.read_csv(obs_file, delimiter=";")

##### Name - Value dict for observation

In [3]:
data = {}
for row in obs_df.iterrows():
    cr = row[1]
    data[cr['name']] = cr['value']

## 10 neighbours

In [4]:
cc = 0
pc = 1
all = len(ip_df)
utc = str(obs_df['utc'][0])
doy = obs_df['doy'][0]
for idx, row in ip_df.iterrows():
    cc = cc+1
    per = (cc/all)*100
    
    ip_df.at[idx, 'utc'] = utc
    ip_df.at[idx, 'doy'] = doy
    ip_df.at[idx, 'value_1'] = data[row['value_1']]
    ip_df.at[idx, 'value_2'] = data[row['value_2']]
    ip_df.at[idx, 'value_3'] = data[row['value_3']]
    ip_df.at[idx, 'value_4'] = data[row['value_4']]
    ip_df.at[idx, 'value_5'] = data[row['value_5']]
    ip_df.at[idx, 'value_6'] = data[row['value_6']]
    ip_df.at[idx, 'value_7'] = data[row['value_7']]
    ip_df.at[idx, 'value_8'] = data[row['value_8']]
    ip_df.at[idx, 'value_9'] = data[row['value_9']]
    ip_df.at[idx, 'value_10'] = data[row['value_10']]
    if per > pc:
        print('{0}: {1:.1f}%'.format(datetime.datetime.now(), pc))
        pc = pc+1

2019-01-05 17:35:13.013838: 1.0%
2019-01-05 17:35:23.190820: 2.0%
2019-01-05 17:35:33.113842: 3.0%
2019-01-05 17:35:43.216819: 4.0%
2019-01-05 17:35:53.634819: 5.0%
2019-01-05 17:36:04.540842: 6.0%
2019-01-05 17:36:14.683826: 7.0%
2019-01-05 17:36:25.188827: 8.0%
2019-01-05 17:36:35.007827: 9.0%
2019-01-05 17:36:44.464843: 10.0%
2019-01-05 17:36:54.087828: 11.0%
2019-01-05 17:37:03.649826: 12.0%
2019-01-05 17:37:13.171842: 13.0%
2019-01-05 17:37:22.571842: 14.0%
2019-01-05 17:37:33.808842: 15.0%
2019-01-05 17:37:43.720842: 16.0%
2019-01-05 17:37:54.776822: 17.0%
2019-01-05 17:38:05.004820: 18.0%
2019-01-05 17:38:14.577842: 19.0%
2019-01-05 17:38:24.157819: 20.0%
2019-01-05 17:38:33.721842: 21.0%
2019-01-05 17:38:43.352826: 22.0%
2019-01-05 17:38:52.938827: 23.0%
2019-01-05 17:39:02.604827: 24.0%
2019-01-05 17:39:12.446819: 25.0%
2019-01-05 17:39:21.969822: 26.0%
2019-01-05 17:39:31.438842: 27.0%
2019-01-05 17:39:40.990826: 28.0%
2019-01-05 17:39:50.756842: 29.0%
2019-01-05 17:40:00.619819: 30.0%
2019-01-05 17:40:10.423842: 31.0%
2019-01-05 17:40:20.291827: 32.0%
2019-01-05 17:40:29.841838: 33.0%
2019-01-05 17:40:39.566827: 34.0%
2019-01-05 17:40:49.542819: 35.0%
2019-01-05 17:40:59.301826: 36.0%
2019-01-05 17:41:09.125842: 37.0%
2019-01-05 17:41:18.789842: 38.0%
2019-01-05 17:41:28.753819: 39.0%
2019-01-05 17:41:38.455842: 40.0%
2019-01-05 17:41:48.274820: 41.0%
2019-01-05 17:41:58.490828: 42.0%
2019-01-05 17:42:08.406842: 43.0%
2019-01-05 17:42:18.224842: 44.0%
2019-01-05 17:42:29.744817: 45.0%
2019-01-05 17:42:39.775819: 46.0%
2019-01-05 17:42:49.655820: 47.0%
2019-01-05 17:42:59.315842: 48.0%
2019-01-05 17:43:09.001820: 49.0%
2019-01-05 17:43:18.755819: 50.0%
2019-01-05 17:43:28.644842: 51.0%
2019-01-05 17:43:38.308820: 52.0%
2019-01-05 17:43:48.228842: 53.0%
2019-01-05 17:43:58.125842: 54.0%
2019-01-05 17:44:08.789820: 55.0%
2019-01-05 17:44:18.893842: 56.0%
2019-01-05 17:44:29.091827: 57.0%
2019-01-05 17:44:39.285842: 58.0%
2019-01-05 17:44:51.064822: 59.0%
2019-01-05 17:45:02.154838: 60.0%
2019-01-05 17:45:12.042827: 61.0%
2019-01-05 17:45:22.246842: 62.0%
2019-01-05 17:45:31.897842: 63.0%
2019-01-05 17:45:42.146827: 64.0%
2019-01-05 17:45:51.840842: 65.0%
2019-01-05 17:46:01.501842: 66.0%
2019-01-05 17:46:11.288826: 67.0%
2019-01-05 17:46:21.172842: 68.0%
2019-01-05 17:46:30.879825: 69.0%
2019-01-05 17:46:40.703842: 70.0%
2019-01-05 17:46:50.520819: 71.0%
2019-01-05 17:47:00.444819: 72.0%
2019-01-05 17:47:10.090827: 73.0%
2019-01-05 17:47:19.794842: 74.0%
2019-01-05 17:47:29.680827: 75.0%
2019-01-05 17:47:39.203842: 76.0%
2019-01-05 17:47:48.729842: 77.0%
2019-01-05 17:47:58.304842: 78.0%
2019-01-05 17:48:07.894819: 79.0%
2019-01-05 17:48:17.574915: 80.0%
2019-01-05 17:48:27.464915: 81.0%
2019-01-05 17:48:37.407032: 82.0%
2019-01-05 17:48:47.100009: 83.0%
2019-01-05 17:48:57.056033: 84.0%
2019-01-05 17:49:06.896033: 85.0%
2019-01-05 17:49:16.917010: 86.0%
2019-01-05 17:49:26.716017: 87.0%
2019-01-05 17:49:36.609014: 88.0%
2019-01-05 17:49:46.305009: 89.0%
2019-01-05 17:49:56.131032: 90.0%
2019-01-05 17:50:05.874017: 91.0%
2019-01-05 17:50:15.558033: 92.0%
2019-01-05 17:50:25.752009: 93.0%
2019-01-05 17:50:35.525033: 94.0%
2019-01-05 17:50:45.193014: 95.0%
2019-01-05 17:50:54.978032: 96.0%
2019-01-05 17:51:04.734014: 97.0%
2019-01-05 17:51:14.497017: 98.0%
2019-01-05 17:51:24.336033: 99.0%

In [8]:
ip_df = ip_df.sort_values(['north', 'east'], ascending=[False, True])

In [9]:
ip_df.head()

,east,north,up,dist_1,value_1,dist_2,value_2,dist_3,value_3,dist_4,...,dist_7,value_7,dist_8,value_8,dist_9,value_9,dist_10,value_10,utc,doy
0,32358000,5811000,31.34,38918.620696,14.1,45564.675042,11.9,53094.848007,13.7,54325.697464,...,62096.868538,24.6,62924.982694,19.8,67052.351488,19.2,69944.509203,13.8,1504828800,251.0
1,32358200,5811000,28.72,38914.446374,14.1,45440.211594,11.9,52930.078451,13.7,54143.632836,...,62108.516585,24.6,62757.222160,19.8,66858.971910,19.2,69915.102856,13.8,1504828800,251.0
2,32358400,5811000,26.88,38911.299381,14.1,45316.288494,11.9,52765.552331,13.7,53961.695041,...,62120.806198,24.6,62589.650898,19.8,66665.630734,19.2,69886.256233,13.8,1504828800,251.0
3,32358600,5811000,25.29,38909.180136,14.1,45192.910544,11.9,52601.272025,13.7,53779.885487,...,62133.737119,24.6,62422.270555,19.8,66472.328759,19.2,69857.970217,13.8,1504828800,251.0
4,32358800,5811000,24.14,38908.088669,14.1,45070.082026,11.9,52437.239751,13.7,53598.205380,...,62147.308855,24.6,62255.082578,19.8,66279.066118,19.2,69830.245379,13.8,1504828800,251.0

In [10]:
file = "prediction_values.csv"
ip_df.to_csv(file, sep=";", index=False)